In [1]:
import pandas as pd
import openensembles as oe
import numpy as np
import re

fileName = 'data_example.csv'
df = pd.DataFrame.from_csv(fileName)
x = [0, 5, 30]
dataObj = oe.data(df, x)

In [2]:
dataObj.D['parent']

array([[ 0. ,  1. ,  1. ],
       [ 0.5,  0.5,  0.5],
       [ 1. ,  1. ,  0. ]])

In [3]:
dataObj

In [4]:
c = oe.cluster(dataObj)

In [6]:
dataObj.transforms_available()

{'log': '', 'minmax': '', 'zscore': ''}

In [7]:
dataObj.transform('parent', 'zscore', 'zscore')
dataObj.D['zscore']

array([[-1.41421356,  0.70710678,  0.70710678],
       [        nan,         nan,         nan],
       [ 0.70710678,  0.70710678, -1.41421356]])

In [8]:
dataObj.transform('parent', 'zscore', 'zscore_noKeep', Keep_NaN=0)
dataObj.D.keys()

Transformation zscore resulted in 3 NaN values, and you requested not to keep a transformation with NaNs


dict_keys(['parent', 'zscore'])

In [9]:
dataObj.transform('parent', 'minmax', 'minmax')
dataObj.D['minmax']

array([[ 0.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  0.]])

In [10]:
dataObj.transform('parent', 'log', 'log_default')
dataObj.D['log_default']

array([[-inf,   0.,   0.],
       [ -1.,  -1.,  -1.],
       [  0.,   0., -inf]])

In [11]:
dataObj.transform('parent', 'log', 'log_10', base=8)
dataObj.D['log_10']

ValueError: Requested base for logarithm was not recognized as either e, 2, or 10)

In [12]:
dataObj.transform('parent', 'logldldkldfklj', 'log_default')

ValueError: The transform function you requested does not exist, currently the following are supported ['log', 'minmax', 'zscore']

In [13]:
dataObj.transform('parent', 'minmax', 'minmaxRangeDiff', minValue=-1, maxValue=1)
dataObj.D['minmaxRangeDiff']

array([[-1.,  1.,  1.],
       [-1., -1., -1.],
       [ 1.,  1., -1.]])

In [14]:
dataObj.transform('parent', 'minmax', 'minmaxRangeDiff', minValue=1, maxValue=-1)

ValueError: Your requested minValue (1.00) is larger than the maximum value (-1.00)